### ISSUE TITLE
APPS - App LIsting - Property 이미지 변경

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#10]
APPS - App LIsting - Property 의 이미지가 없습니다. 다음 이미지를 넣어주세요.
![IDH1 ss q3 prob](https://user-images.githubusercontent.com/45085754/149701549-11e4cbed-6568-48d6-8a95-e0270ca4d92f.png)

**Comment by arontier-hjchoi** [comment]
개발서버에 이미지 반영했습니다. 
Property 외에도 이미지가 없는 app이 있으며, 아래 링크에서 같이 확인이 가능합니다.
기존의 아이콘들에서 사용한 이미지를 짜집기하여 새로운 아이콘을 만들순 있습니다. 적당한 이미지가 있다면 알려주세요.
http://frontend.arontier.co.kr/app-listing (MolFinder Scaffolds, MolFinder De Novo, Patent Search, Molecule Editor, Protein Viewer)

**Comment by arontier-hjchoi** [comment]
해당 이슈 완료되어 닫습니다.
