### ISSUE TITLE
APPS - HIT DISCOVERY - MolFinder Scaffolds를 LEAD OPTIMIZATION으로 옮겨주세요.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#11]
APPS - HIT DISCOVERY - MolFinder Scaffolds를 LEAD OPTIMIZATION으로 옮겨주세요.
(MolFinder de novo는 HIT DISCOVERY에 있어야 합니다.)

**Comment by arontier-hjchoi** [comment]
[개발서버](http://frontend.arontier.co.kr/molfinder/jobs)엔 반영되었고, 상용서버엔 이번주 내로 반영될 예정입니다.
