### ISSUE TITLE
이 메일 제목에 App 이름과 본문에 job link 가 제공되면 좋겠습니다.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#13]
Job 이 끝나면 이멩리이 오는데, 같은 단백질 이름을 사용하니까 제목이 동일하게 외서 어던 작업인지 모르겠네요.

Title 에 App 이름을 추가,
본문에 Job 바로가기 link 가 추가

되면 좋겠습니다.

**Comment by arontier-egkim** [comment]
상용서버에 반영되었습니다.

backend version 1.9.5, 
frontend version 1.8.6

backend commit 05a56c2c742d633a40cb72d8436ae5c747cffa14
frontend commit b0c7ee87fba8efcf8b9781654d779928378f969d

완료되어 해당 이슈를 닫습니다.
