### ISSUE TITLE
각 App 의 New Job 에 Example 데이터가 있으며 좋겠습니다.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#15]
각 App의 New Job에 Example 데이터가 있으면 좋겠습니다.

**Comment by arontier-hjchoi** [comment]
각 App, Database의 help page와 연동되는 [ad3-frontend-tutorials(github)](https://github.com/arontier/ad3-frontend-tutorials)을 만들었습니다.
- apps/{app name}/dose/en/README.md의 Inputs에 Example 데이터에 대한 정보를 명시했습니다.
- 현재 개발서버엔 [main branch](https://github.com/arontier/ad3-frontend-tutorials), 상용서버엔 [1.0.1 tag](https://github.com/arontier/ad3-frontend-tutorials/releases/tag/1.0.1)가 적용 되어있습니다.

- frontend commit [d871e9cbe1feb2b26287c501665a36b9b7151c81](https://gitlab.com/arontier/ad3/aid-frontend/-/commit/d871e9cbe1feb2b26287c501665a36b9b7151c81)
- frontend release [1.8.8](https://gitlab.com/arontier/ad3/aid-frontend/-/releases/1.8.8)

완료되어 해당 이슈를 닫습니다.
