### ISSUE TITLE
Complex 모델링 실패 원인이 필요합니다

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#17]
Job 1904
Job 1905

작업이 실패했습니다. 원인을 알고 싶습니다.

**Comment by arontier-dmjeong** [comment]
에러 메시지는 다음과 같습니다.

```python
Traceback (most recent call last):
  File "run_AK_fold.py", line 600, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_AK_fold.py", line 554, in main
    input_seqs, input_descs = parsers.parse_fasta(input_fasta_str)
  File "/app/alphafold/data/parsers.py", line 63, in parse_fasta
    sequences[index] += line
IndexError: list index out of range
```

에러의 원인은 sequence의 name이 없기 때문으로 판단됩니다. 입력하신 file은 다음과 같습니다.
```
MPGIKRILTVTILALCLPSPGNAQAQCTNGFDLDRQSGQCLDIDECRTIPEACRGDMMCV
NQNGGYLCIPRTNPVYRGPYSNPYSTPYSGPYPAAAPPLSAPNYPTISRPLICRFGYQMD
ESNQCV
```

**Comment by jsko-arontier** [comment]
sequence name 이 없을 경우 임의의 이름을 넣어서 동작 시켜주셔야 할 것 같습니다.

웹 인터페이스에 sequence name 이 없어도 작동할 수 있도록 되어 있고,
실제 사용자들이 그렇게 할 수도 있을 것 같습니다.

**Comment by arontier-hjchoi** [comment]
[개발서버](http://frontend.arontier.co.kr/afold/submission/)에 우선 반영 되었습니다.
- text로 입력한 sequence의 name이 없을 경우, 임의의 이름 생성되도록 수정
    - frontend commit [9bae62836ac583fd897391910b90aaa9b27afcff](https://gitlab.com/arontier/ad3/aid-frontend/-/commit/9bae62836ac583fd897391910b90aaa9b27afcff), [2de881f1beba3cc57702c0160fabf2f50435fb64](https://gitlab.com/arontier/ad3/aid-frontend/-/commit/2de881f1beba3cc57702c0160fabf2f50435fb64)
    
상용서버에 적용 후 comment 추가 하겠습니다.

**Comment by arontier-hjchoi** [comment]
[상용서버](https://www.ad3.io/afold/submission/)에 적용되었습니다.

**Comment by arontier-hjchoi** [comment]
[상용서버](https://www.ad3.io/afold/submission/)에 적용되었습니다.
 - frontend release [1.8.9](https://gitlab.com/arontier/ad3/aid-frontend/-/releases/1.8.9)
완료되어 해당 이슈를 닫습니다.
