### ISSUE TITLE
TARGET -> Property 에서 Sequence 입력란이 너무 작습니다.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#2]
TARGET -> Property 에서 Sequence 입력란이 너무 작습니다.

**Comment by arontier-hjchoi** [comment]
[개발서버](http://frontend.arontier.co.kr/protein-properties/jobs)에 수정하여 반영했습니다.
상용서버엔 다음번 패치에 반영될 예정입니다.

**Comment by jsko-arontier** [comment]
확인했습니다. 괜찮은 것 같습니다.
