### ISSUE TITLE
각 Pipeline의 Report Title 이 "Job Name + Job Description" 형식으로 바꿔주세요.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#20]
현재 각 분석 프로그램의 분석 후 레포트 제목이 다음과 같이 나옵니다.

"V-Dock Hit Screening Report"
"Protein Structure Prediction Report"

이렇게 나오니까 레포트를 보고 있을때 어떤 작업의 레포트를 보는지 모르겠습니다.
작업의 입력 값이 나오면 좋겠습니다.

"{NAME} : {Description}"

예를 들면, Job 1912, 1911 경우 다음과 같이 나오면 좋겠습니다.

"FBLN5_1-126	: FBLN5 Monomer (1-126) [af2_stair,ensembl,20]"
"FBLN5_Dimer : FBLN5 Dimer (1-126) [af2_stair,ensembl,20]"

**Comment by arontier-hjchoi** [comment]
기존 JobCard에서 id, uuid가 표기되던 부분을  name, description으로 수정하여 반영 하였습니다.
예로 들어주신 "FBLN5_1-126 : FBLN5 Monomer (1-126) [af2_stair,ensembl,20]"의 경우 아래의 이미지처럼 보여질 것 입니다.
- frontend commit [e715c24521b1b8b15491ea86802ba714bfb476b3](https://gitlab.com/arontier/ad3/aid-frontend/-/commit/e715c24521b1b8b15491ea86802ba714bfb476b3)
- frontend releases [1.8.9](https://gitlab.com/arontier/ad3/aid-frontend/-/releases/1.8.9)

완료되어 해당 이슈를 닫습니다.

![image](https://user-images.githubusercontent.com/74892597/151088368-43a92c56-b053-4e70-9249-6f88d0ae6298.png)
