### ISSUE TITLE
TARGET 화면에  목차를 넣어주세요.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#21]
Target 화면에 목차가 없습니다. Compounds 처럼 CONTENTS 가 있었으면 합니다.

예)
https://www.ad3.io/pub-targets/253
https://www.ad3.io/compounds/compounds/4

**Comment by arontier-hjchoi** [comment]
[개발서버](http://frontend.arontier.co.kr/pub-targets/253)에 우선 반영 되었습니다.
Database의 [Targets](http://frontend.example/targets/targets/253)에도 함께 반영 되었습니다. 
- frontend commit [db4f11f4292a23679c828be721a4eb656d4f5e0c](https://gitlab.com/arontier/ad3/aid-frontend/-/commit/db4f11f4292a23679c828be721a4eb656d4f5e0c)

상용서버에 적용 후 comment 추가 하겠습니다.

**Comment by arontier-hjchoi** [comment]
[상용서버](https://www.ad3.io/pub-targets/253)에 적용되었습니다.
 - frontend release [1.8.9](https://gitlab.com/arontier/ad3/aid-frontend/-/releases/1.8.9)
완료되어 해당 이슈를 닫습니다.
