### ISSUE TITLE
TARGETS 삭제 기능이 필요합니다. 

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#23]
TARGETS 에서 필요없는 TARGET 제거를 삭제하는 기능이 필요합니다.

**Comment by arontier-hjchoi** [comment]
[상용서버](https://www.ad3.io/workspaces/targets/)에 적용되었습니다.

**Comment by arontier-hjchoi** [comment]
[상용서버](https://www.ad3.io/workspaces/targets/)에 적용되었습니다.
목록 페이지에서 선택하여 삭제하거나 상세페이지 탭 아래 우측 상단에 delete 버튼으로 삭제할 수 있습니다.
- frontend commit [c92b428ddda21468f8a4d1a3697a898279d0272e](https://gitlab.com/arontier/ad3/aid-frontend/-/commit/c92b428ddda21468f8a4d1a3697a898279d0272e)
- frontend release [2.0.0](https://gitlab.com/arontier/ad3/aid-frontend/-/releases/2.0.0)
- backend commit [61b9661209ecf2440e4ef1b0d7b2ee7e083c6c1b]https://gitlab.com/arontier/ad3/aid-backend/-/commit/61b9661209ecf2440e4ef1b0d7b2ee7e083c6c1b
- backend release [2.1.0](https://gitlab.com/arontier/ad3/aid-backend/-/releases/2.1.0)
완료되어 해당 이슈를 닫습니다.
