### ISSUE TITLE
등록된 TARGET에 대해서 "Edit Target" 기능이 안됩니다.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#24]
TARGETS 에서 Target 설명 페이지에 들어가면  "Edit Target"이 있는데, 어떤 기능인지 작동이 안되네요.

**Comment by arontier-hjchoi** [comment]
상세 페이지를 업데이트 하면서 'Edit Target' 버튼을 없앴습니다.
 업데이트된 상세페이지는 [상용서버](https://www.ad3.io/workspaces/targets/)에 적용되었습니다.
- frontend commit [e1dd009dc761b95152e4555636ddafd6aaf5855d](https://gitlab.com/arontier/ad3/aid-frontend/-/commit/e1dd009dc761b95152e4555636ddafd6aaf5855d)
- frontend release [2.0.0](https://gitlab.com/arontier/ad3/aid-frontend/-/releases/2.0.0)
완료되어 해당 이슈를 닫습니다.
