### ISSUE TITLE
TARGETS 의 세부 페이지에서 구조가 등록된 경우에도 구조가 나오지 않습니다.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#25]
TARGETS에서 새로운 Target을 을 등록할때 PDB로 진행을 하더라도 등록 이후에 구조가 나오지 않습니다.

**Comment by arontier-hjchoi** [comment]
[상용서버](https://www.ad3.io/workspaces/targets/)에 상세페이지가 업데이트 되었습니다.
- frontend commit [e1dd009dc761b95152e4555636ddafd6aaf5855d](https://gitlab.com/arontier/ad3/aid-frontend/-/commit/e1dd009dc761b95152e4555636ddafd6aaf5855d)
- frontend release [2.0.0](https://gitlab.com/arontier/ad3/aid-frontend/-/releases/2.0.0)
완료되어 해당 이슈를 닫습니다.
