### ISSUE TITLE
TARGETS에서 표적 등록 후 여러개의 구조를 추가 등록할 수 있어야 합니다.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#26]
TARGETS에 표적 등록후 여러게의 단백질 구조를 등록할 수 있어야 합니다.

TARGETS에 예를 들어 다음 서열을 이용해서 표적을 등록합니다.

```
>sp|O15427|MOT4_HUMAN Monocarboxylate transporter 4 OS=Homo sapiens OX=9606 GN=SLC16A3 PE=1 SV=1
MGGAVVDEGPTGVKAPDGGWGWAVLFGCFVITGFSYAFPKAVSVFFKELIQEFGIGYSDT
AWISSILLAMLYGTGPLCSVCVNRFGCRPVMLVGGLFASLGMVAASFCRSIIQVYLTTGV
ITGLGLALNFQPSLIMLNRYFSKRRPMANGLAAAGSPVFLCALSPLGQLLQDRYGWRGGF
LILGGLLLNCCVCAALMRPLVVTAQPGSGPPRPSRRLLDLSVFRDRGFVLYAVAASVMVL
GLFVPPVFVVSYAKDLGVPDTKAAFLLTILGFIDIFARPAAGFVAGLGKVRPYSVYLFSF
SMFFNGLADLAGSTAGDYGGLVVFCIFFGISYGMVGALQFEVLMAIVGTHKFSSAIGLVL
LMEAVAVLVGPPSGGKLLDATHVYMYVFILAGAEVLTSSLILLLGNFFCIRKKPKEPQPE
VAAAEEEKLHKPPADSGVDLREVEHFLKAEPEKNGEVVHTPETSV
```

이후 첨부되어 있는 파일 4개를 추가 구조로 등록할 수 있어야 합니다.
[MCT4_structures.zip](https://github.com/arontier/ad3/files/8052246/MCT4_structures.zip)

**Comment by arontier-hjchoi** [comment]
[상용서버](https://www.ad3.io/workspaces/targets/)에 적용되었습니다.
상세페이지의 Structures table에서 "Click here ..."을 누르거나 drag and drop으로 여러 Structures를  업로드 할 수 있습니다.
- frontend commit [0d60dd8337b7abda034855d66db6b007686332d3](https://gitlab.com/arontier/ad3/aid-frontend/-/commit/0d60dd8337b7abda034855d66db6b007686332d3)
- frontend release [2.0.0](https://gitlab.com/arontier/ad3/aid-frontend/-/releases/2.0.0)
- backend commit [4681bd7c4fc18877287c02bd518a27492949fa4a](https://gitlab.com/arontier/ad3/aid-backend/-/commit/4681bd7c4fc18877287c02bd518a27492949fa4a)
- backend release [2.1.0](https://gitlab.com/arontier/ad3/aid-backend/-/releases/2.1.0)
완료되어 해당 이슈 닫습니다.
