### ISSUE TITLE
Target DB 페이지에 References 가 필요합니다.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#4]
웹사이트는 각 페이지에 References 가 없네요.
우선 Targets의 각 페이지에 다음 정보를 추가해주세요.

* Cho, E. J. et al. Immuno-genomic classification of colorectal cancer organoids reveals cancer cells with intrinsic immunogenic properties associated with patient survival. J Exp Clin Canc Res 40, 230 (2021).
* Jumper, J. et al. Highly accurate protein structure prediction with AlphaFold. Nature 1–11 (2021) doi:10.1038/s41586-021-03819-2.
* TCGA : The results shown here are in whole or part based upon data generated by the TCGA Research Network: https://www.cancer.gov/tcga
* Tsherniak, A. et al. Defining a Cancer Dependency Map. Cell 170, 564-576.e16 (2017).
* Varadi, M. et al. AlphaFold Protein Structure Database: massively expanding the structural coverage of protein-sequence space with high-accuracy models. Nucleic Acids Res 50, D439–D444 (2022).

**Comment by arontier-hjchoi** [comment]
상용 사이트에 Targets에 대한 References 반영했습니다.
https://www.ad3.io/pub-targets/655
