### ISSUE TITLE
AK-score 웹레포트가 나오지 않습니다. 

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#6]
AK-score를 돌렸는데, 웹레포트가 나오지 습니다.
output 파일에 결과는 정상적으로 나타납니다.

**Comment by arontier-hjchoi** [comment]
상용과 개발에 모두 업데이트 하였습니다.
결과를 볼 수 있는 Job을 Share 하여 아래 링크에서 확인이 가능합니다.
https://www.ad3.io/ak-scores/jobs/1516/
