### ISSUE TITLE
V-Dock 입력이 되지 않습니다.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#7]
V-Dock 작업이 들어가지 않습니다.  스크린샷 첨부합니다.

---

![Discovery_V-Dock_Input](https://user-images.githubusercontent.com/45085754/149696800-7796d0ae-5b0c-48ec-967f-d5015b1fb597.png)

**Comment by arontier-dmjeong** [comment]
해당 이슈는 DB에서 box-center Field가 CharField로 되어있어 지정 해놓은 글자 수 200 글자를 넘어 등록이 되지 않았습니다. 
box-center의 field를 TextField로 수정하여 version 1.9.2로 상용에 반영하였습니다. 
감사합니다. 

https://gitlab.com/arontier/ad3/aid-backend/-/releases/1.9.2
