### ISSUE TITLE
SPICA New Job 화면의 화합물 입력을 Patent Search와 같이 해주세요.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#8]
SPICA New Job 화면의 화합물 입력을 Patent Search와 같이 해주세요.

**Comment by arontier-hjchoi** [comment]
상용서버에 반영되었습니다.

  - frontend commit [69fbd2b1db6e264deb7cee524738efa4542bc4cd](https://gitlab.com/arontier/ad3/aid-frontend/-/commit/69fbd2b1db6e264deb7cee524738efa4542bc4cd)
  - frontend release [1.8.8](https://gitlab.com/arontier/ad3/aid-frontend/-/releases/1.8.8)

완료되어 해당 이슈를 닫습니다.
