### ISSUE TITLE
COMPOUND LIBRARIES 에서 "DRAW COMPOUND", "UPLOAD COMPOUNDS"가 작동되지 않습니다.

### ISSUE THREAD

**Issue by jsko-arontier** [arontier/ad3#9]
COMPOUND LIBRARIES 에서 "DRAW COMPOUND", "UPLOAD COMPOUNDS"가 작동되지 않습니다.

DRAW COMPOUND는 SEARCH로 넘어가고,
UPLOAD COMPOUNDS는 반응이 없습니다.

**Comment by arontier-hjchoi** [comment]
현재 'DRAW COMPOUND'와 'UPLOAD COMPOUNDS'는 불가능한 상태라 상용 사이트엔 일단 숨겨두었습니다.
